### ISSUE TITLE
Selecting multiple fields

### ISSUE THREAD

**Issue by epistularum** [tsudoko/kanjigrid#7] opened 2019-01-09 16:13 UTC
I can't seem to input multiple fields.

**Comment by tsudoko** [comment] 2019-01-09 20:46
> Searching for "kyuujitai_jinmeiyou, shinjitai" result in only the "shinjitai" field being calculated.
Putting the field in the opposite order ("shinjitai, kyuujitai_jinmeiyou") results in only the "kyuujitai_jinmeiyou" field being calculated.

That's because you're supposed to separate field names with spaces (yes, there's currently no way to use fields with spaces in names). What happens when you enter both field names, separated by spaces, with the "Match exactly" option turned on?

> Sometimes when you input a kyuujitai kanji into anki 2.1 and change to another card, the kyuujitai kanji gets modified into its shinjitai form automatically.

If I'm not mistaken, this is the cause:
https://github.com/dae/anki/blob/2a539cda1bc5849c45669a75b56b92b74fbd805f/aqt/editor.py#L256

I don't know why it was introduced, but [it seems to have been intentional](https://github.com/dae/anki/commit/6335dcb90e60c25647cbbbe66d69c9d157b27ed4), you might want to bring this up on the support site.

**Comment by epistularum** [comment] 2019-01-09 21:08
>That's because you're supposed to separate field names with spaces (yes, there's currently no way to use fields with spaces in names). What happens when you enter both field names, without any quoting, separated by spaces, with the "Match exactly" option turned on?

My fields do not have a space in them. And when I enter both field names, without any quoting, separated by spaces, with the "Match exactly" option turned on, the same result occurs where depending on the order I put the fields, one gets calculated and not the other (same result as with a "," stated above).
Meaning that searching for "kyuujitai_jinmeiyou shinjitai" results in only the "shinjitai" field being calculated and putting the field in the opposite order ("shinjitai kyuujitai_jinmeiyou") results in only the "kyuujitai_jinmeiyou" field being calculated.

>If I'm not mistaken, this is the cause:
https://github.com/dae/anki/blob/2a539cda1bc5849c45669a75b56b92b74fbd805f/aqt/editor.py#L256
I don't know why it was introduced, but it seems to have been intentional, you might want to bring this up on the support site.

That seems like a really weird change to make, considering that the jinmeiyou kanji list are in common use.
I've already posted a ticket concerning this matter.

**Comment by tsudoko** [comment] 2019-01-09 22:15
> That seems like a really weird change to make, considering that the jinmeiyou kanji list are in common use.

Well, the ones affected by this bug aren't very common, since they're just minor variants of the commonly used ones.

Thanks for reporting, this is a pretty serious issue I didn't notice because each field I specify is in a different note type. Should be fixed in the version in the repo, I'll update the AnkiWeb addon if you confirm it works for you too.

**Closed** 2019-01-09 22:15 UTC

**Comment by epistularum** [comment] 2019-01-09 22:18
> Well, the ones affected by this bug aren't very common, since they're just minor variants of the commonly used ones.

Still fairly important !

> Thanks for reporting, this is a pretty serious issue I didn't notice because each field I specify is in a different note type. Should be fixed in the version in the repo, I'll update the AnkiWeb addon if you confirm it works for you too.

Glad I could help, I'll try it out

**Comment by epistularum** [comment] 2019-01-10 01:49
Additional info:
The issue I talked about with some kyuujitai not being calculated by the addon is now fixed.
I'm not sure what fixed it but it may the commit.
